@startuml ankh-uml
title Call Stack

class IdManager
{
  -id
  +generateId()
}

class WebsiteVerifier
{
  +verify()
}

class AddressService
{
  -zipCityMap
  +getCityByZip()
}

class Address
{
  -address
  +getAddress()
}

class User
{
  -id
  -email
  -username
  -address
  -website
  -websiteVerifier
  +getUser()
  -verifyEmail()
}


Address --> AddressService
User --> IdManager
User --> WebsiteVerifier
User --> Address

@enduml